import { Injectable } from '@angular/core';
import { Product } from '../model/product';

@Injectable({
  providedIn: 'root'
})
export class ProductService {
  list: Product[] = [
    {
      id: 1,
      catId: 0,
      name: "Star Wars: X-Wing vs. TIE Fighter nagydobozos (német dobozos angol)",
      description: "papírdobozos, első kiadás, német feliratos papírdobozos, német nyelvű papírkézikönyv + telepítési útmutató + útmutató, cd tokban az eredeti 2 cd, angol nyelvű játék. CD-k állapota: enyhén-közepesen karcos (hajszálkarcok), tesztelt, működik",
      image: "http://www.retro-games.hu/images/stories/virtuemart/product/PCBOX0306.jpg",
      price: 2500,
      stock: 1,
      featured: true,
      active: true,
      onsale: false
    },
    {
      id: 2,
      catId: 0,
      name: "Painkiller: Limited Black Edition 2012 (Battle Out of Hell is benne)",
      description: "dvd tokos, első kiadás papírtokban, angol feliratos borító, poszter, eredeti dvd, angol nyelvű játék. DVD állapota: karcmentes, újnak tűnik. Megjegyzés: van benne egy Steam kulcs, ami valószínűleg el lett használva, de a játék telepítéséhez és futtatásához nem kell Steam és aktiválás",
      image: "http://www.retro-games.hu/images/stories/virtuemart/product/PCBOX0403.jpg",
      price: 3000,
      stock: 1,
      featured: false,
      active: true,
      onsale: false
    },
    {
      id: 3,
      catId: 0,
      name: "The Temple of Elemental Evil (papírdobozos)",
      description: "papírdobozos, angol feliratos borító, angol nyelvű papírkézikönyv, eredeti 2cd, angol nyelvű játék. karcmentes, újnak tűnik",
      image: "http://www.retro-games.hu/images/stories/virtuemart/product/PCBOX0404.jpg",
      price: 4000,
      stock: 1,
      featured: true,
      active: true,
      onsale: false
    },
    {
      id: 4,
      catId: 0,
      name: "Paraworld",
      description: "mini papírdobozos, első kiadás, német feliratos papírdoboz, német nyelvű papírkézikönyv, eredeti cd, német/angol nyelvű  játék. CD állapota: szinte karcmentes, tesztelt, működik",
      image: "http://www.retro-games.hu/images/stories/virtuemart/product/PCBOX0410.jpg",
      price: 3000,
      stock: 1,
      featured: false,
      active: true,
      onsale: false
    },
    {
      id: 5,
      catId: 0,
      name: "Baldur's Gate II: Schatten von Amn (Shadows of Amn) (német)",
      description: "papírdobozos, első kiadás, német kiadás, speciális kihajtható előlapos német feliratos papírdobozos, quick reference card, kihajtható színes papírtérkép, papírkézikönyv (mind német nyelvű), eredeti vaskos cd tokjában az eredeti 4cd, német nyelvű játék. CD-k állapota: karcmentes, újnak tűnik.",
      image: "http://www.retro-games.hu/images/stories/virtuemart/product/PCBOX050.jpg",
      price: 3000,
      stock: 1,
      featured: false,
      active: true,
      onsale: false
    },
    {
      id: 6,
      catId: 0,
      name: "Grand Prix 3 (Microprose, Geoff Crammond) (német)",
      description: "papírdobozos, első kiadás, német feliratos papírdoboz, német nyelvű papírkézikönyv, cd tokban az eredeti cd, német nyelvű játék. CD állapota: karcmentes, újnak tűnik",
      image: "http://www.retro-games.hu/images/stories/virtuemart/product/PCBOX053.jpg",
      price: 4000,
      stock: 1,
      featured: false,
      active: true,
      onsale: false
    },
    {
      id: 7,
      catId: 0,
      name: "Icewind Dale (német)",
      description: "papírdobozos, első kiadás, német kiadás, német feliratos papírdobozos, quick reference card, kihajtható színes papírtérkép, papírkézikönyv (mind német nyelvű), eredeti cd tokjában az eredeti 2cd, német nyelvű játék. CD-k állapota: karcmentes, újnak tűnik",
      image: "http://www.retro-games.hu/images/stories/virtuemart/product/PCBOX055.jpg",
      price: 3000,
      stock: 1,
      featured: false,
      active: true,
      onsale: false
    },
    {
      id: 8,
      catId: 0,
      name: "Shogun: Total War",
      description: "papírdobozos, első kiadás, magyar feliratos papírdobozos (a doboz megviselt állapotú), magyar nyelvű papírkézikönyv, cd tokban az eredeti 2 cd, angol nyelvű játék. CD-k állapota: karcmentes, újnak tűnik",
      image: "http://www.retro-games.hu/images/stories/virtuemart/product/PCBOX060.jpg",
      price: 5000,
      stock: 1,
      featured: true,
      active: true,
      onsale: false
    },
    {
      id: 9,
      catId: 0,
      name: "The Sims 1: Livin' It Up kiegészítő lemez",
      description: "papírdobozos, első kiadás, magyar feliratos papírdobozos, magyar nyelvű útmutató, cd tokban az eredeti cd, angol nyelvű kiegészítő lemez, a Sims 1 alapjáték szükséges hozzá! CD állapota: karcmentes, újnak tűnik",
      image: "http://www.retro-games.hu/images/stories/virtuemart/product/PCBOX063.jpg",
      price: 4000,
      stock: 1,
      featured: false,
      active: true,
      onsale: false
    },
    {
      id: 10,
      catId: 0,
      name: "Carmageddon + Speed Haster + Hard Core 4x4 egyben",
      description: "papírdobozos, Diamond Collection kiadás, angol feliratos papírdobozos, 3 db angol nyelvű kis papírkézikönyv mindegyik játékhoz külön, tokokban az eredeti 3 cd, angol nyelvű játékok. CD állapota: szinte karcmentes, tesztelt, működik",
      image: "http://www.retro-games.hu/images/stories/virtuemart/product/PCBOX068.jpg",
      price: 9000,
      stock: 1,
      featured: false,
      active: true,
      onsale: false
    },
    {
      id: 11,
      catId: 0,
      name: "Play the Games Vol. 2. 15 játék egyben (német)",
      description: "tartalma: Command & Conquer Red Alert, Warhammer: Dark Omen, Sid Meier's Gettysburg, Superbike World Championship, Future Cop LAPD, Heart of Darkness, V-Rally, Herrscher der Meere, Airline Tycoon, Die Schlümpfe: Der Teletransportierschlumpf, Gangsters, Tomb Raider II, Deathtrap Dungeon, Flight Unlimited II, World League Soccer '98. papírdobozos, gyűjteményes kiadás, német feliratos papírdobozos, német nyelvű papírkézikönyv, tokokban az eredeti cd-k, német nyelvű játékok. CD állapota: karcmentes, újnak tűnik",
      image: "http://www.retro-games.hu/images/stories/virtuemart/product/PCBOX069.jpg",
      price: 5000,
      stock: 1,
      featured: false,
      active: true,
      onsale: false
    },
    {
      id: 12,
      catId: 0,
      name: "Steel Thunder: American Battle Tank Simulation",
      description: "papírdobozos (a doboz sérült), eredeti kiadás, angol feliratos papírdoboz, angol nyelvű papírkézikönyv, billentyűzetkiosztás, 1 x 3.5 floppy, angol nyelvű játék.",
      image: "http://www.retro-games.hu/images/stories/virtuemart/product/PCBOX071.jpg",
      price: 2000,
      stock: 1,
      featured: false,
      active: true,
      onsale: false
    },
    {
      id: 13,
      catId: 0,
      name: "MTV's Slam Scape",
      description: "papírdobozos, első kiadás, angol/német/francia/spanyol/olasz feliratos papírdobozos, angol/német/francia/spanyol/olasz nyelvű papírkézikönyv, cd tokban az eredeti cd, angol nyelvű játék. CD állapota: szinte karcmentes, tesztelt, működik.",
      image: "http://www.retro-games.hu/images/stories/virtuemart/product/PCBOX073.jpg",
      price: 4000,
      stock: 1,
      featured: false,
      active: true,
      onsale: false
    },
    {
      id: 14,
      catId: 1,
      name: "A keresztapa 2 (The Godfather II 2)",
      description: "dvd tokos, EA Classics kiadás, magyar feliratos borító, eredeti dvd, angol nyelvű játék. DVD állapota: szinte karcmentes, tesztelt, működik. A játék telepítéséhez internetkapcsolat és aktiválás szükséges. Még van szabad aktiválás, így telepíthető és használható (tesztelve lett).",
      image: "http://www.retro-games.hu/images/stories/virtuemart/product/PCDVD7418.jpg",
      price: 2000,
      stock: 1,
      featured: false,
      active: true,
      onsale: false
    },
    {
      id: 15,
      catId: 1,
      name: "Acélszív (Hearts of Iron)",
      description: "dvd tokos, első kiadás, magyar feliratos borító, magyar nyelvű papírkézikönyv, eredeti cd, magyar feliratos játék. CD állapota:  karcmentes, újnak tűnik",
      image: "http://www.retro-games.hu/images/stories/virtuemart/product/PCDVD7421.jpg",
      price: 4000,
      stock: 1,
      featured: true,
      active: true,
      onsale: false
    },
    {
      id: 16,
      catId: 1,
      name: "Age of Empires Gold Edition (Rise of Rome is)",
      description: "dvd tokos, Ubisoft Exclusive kiadás, magyar/angol/olasz feliratos borító, eredeti cd, angol nyelvű játék. Ez a kiadás tartalmazza az Age of Empires 1 alapjátékot és a The Rise of Rome kiegészítő lemezt. CD állapota: szinte karcmentes, tesztelt, működik.",
      image: "http://www.retro-games.hu/images/stories/virtuemart/product/PCDVD7426.jpg",
      price: 1500,
      stock: 1,
      featured: false,
      active: true,
      onsale: false
    },
    {
      id: 17,
      catId: 1,
      name: "Anno 1503 Gold Edition (The New World + Treasures, Monsters & Pirates kiegészítő)",
      description: "dvd tokos, első kiadás, angol/magyar feliratos borító, eredeti dvd, angol nyelvű játék. DVD állapota: karcmentes, újnak tűnik",
      image: "http://www.retro-games.hu/images/stories/virtuemart/product/PCDVD6832.jpg",
      price: 4000,
      stock: 1,
      featured: false,
      active: true,
      onsale: false
    },
    {
      id: 18,
      catId: 1,
      name: "Baldur's Gate + Tales of the Sword Coast",
      description: "dvd tokos, első kiadás, angol/francia feliratos borító, eredeti 3 cd, angol nyelvű játék + kiegészítője. CD-k állapota: enyhén-közepesen karcos (hajszálkarcok), tesztelt, működik.",
      image: "http://www.retro-games.hu/images/stories/virtuemart/product/PCDVD7036.jpg",
      price: 2500,
      stock: 1,
      featured: false,
      active: true,
      onsale: false
    },
    {
      id: 19,
      catId: 1,
      name: "Battlefield 2 Complete Collection (Special Forces, Euro Forces és Armored Fury is)",
      description: "dvd tokos, utánkiadás, magyar feliratos borító, magyar nyelvű papírkézikönyv, eredeti dvd, angol nyelvű játék. Tartalma: Battlefield 2 + Special Forces, Euro Forces és Armored Fury kiegészítők. DVD állapota: enyhén-közepesen karcos (hajszálkarcok), tesztelt, működik.",
      image: "http://www.retro-games.hu/images/stories/virtuemart/product/PCDVD7622.jpg",
      price: 2500,
      stock: 1,
      featured: false,
      active: true,
      onsale: false
    },
    {
      id: 20,
      catId: 1,
      name: "Beyond Good & Evil",
      description: "dvd tokos, első kiadás, magyar feliratos borító, magyar nyelvű rövid papírkézikönyv, eredeti 3 cd, angol nyelvű játék. CD-k állapota: szinte karcmentes, tesztelt, működik",
      image: "http://www.retro-games.hu/images/stories/virtuemart/product/PCDVD7189.jpg",
      price: 3500,
      stock: 1,
      featured: false,
      active: true,
      onsale: false
    },
    {
      id: 21,
      catId: 1,
      name: "Black & White 2 Collector's Edition",
      description: "dvd tokos, első kiadás, angol feliratos borító, angol nyelvű papírkézikönyv, eredeti 2dvd (játék + bónusz Making of DVD), angol nyelvű játék. Bónusz játszható lény: a tigris. DVD-k állapota: enyhén karcos (hajszálkarcok), tesztelt, működik",
      image: "http://www.retro-games.hu/images/stories/virtuemart/product/PCDVD7625.jpg",
      price: 4000,
      stock: 1,
      featured: false,
      active: true,
      onsale: false
    },
    {
      id: 22,
      catId: 1,
      name: "Blair Witch Volume I: Rustin Parr",
      description: "dvd tokos, EVM utánkiadás, magyar feliratos borító, eredeti cd, angol nyelvű játék. CD állapota: karcmentes, újnak tűnik",
      image: "http://www.retro-games.hu/images/stories/virtuemart/product/PCDVD5809.jpg",
      price: 2000,
      stock: 1,
      featured: false,
      active: true,
      onsale: false
    },
    {
      id: 23,
      catId: 1,
      name: "Brothers In Arms Collection (Road to Hill 30 + Earned in Blood + Hell's Highway)",
      description: "dvd tokos, utánkiadás, angol/francia/holland feliratos borító, eredeti DVD, angol nyelvű játékgyűjtemény. DVD állapota: karcmentes, újnak tűnik",
      image: "http://www.retro-games.hu/images/stories/virtuemart/product/PCDVD7717.jpg",
      price: 5000,
      stock: 1,
      featured: false,
      active: true,
      onsale: false
    },
    {
      id: 24,
      catId: 1,
      name: "Caesar IV",
      description: "dvd tokos, első kiadás, magyar feliratos borító, magyar nyelvű papírkézikönyv, eredeti 2 cd, magyar nyelvű játék. CD-k állapota: karcmentes, újnak tűnik",
      image: "http://www.retro-games.hu/images/stories/virtuemart/product/PCDVD7191.jpg",
      price: 3000,
      stock: 1,
      featured: false,
      active: true,
      onsale: false
    },
    {
      id: 25,
      catId: 1,
      name: "Call of Duty 4: Modern Warfare",
      description: "dvd tokos, első kiadás, magyar feliratos borító, magyar nyelvű papírkézikönyv, eredeti dvd, CD-kulcs, angol nyelvű játék. A cd-kulcs nem tudom, hogy el lett-e használva multiplayerre (erre nem vállalunk garanciát), offline egyjátékos módban működik biztosan. DVD állapota: karcmentes, újnak tűnik",
      image: "http://www.retro-games.hu/images/stories/virtuemart/product/PCDVD6773.jpg",
      price: 3000,
      stock: 1,
      featured: false,
      active: true,
      onsale: false
    },
    {
      id: 26,
      catId: 1,
      name: "Call of Duty 4: Modern Warfare Game of the Year Edition",
      description: "dvd tokos, Game of the Year kiadás, angol feliratos borító, angol nyelvű papírkézikönyv, eredeti dvd, angol nyelvű játék. DVD állapota: enyhén karcos (hajszálkarcok), tesztelt, működik. Hozzám használtan került, nem tudom, hogy a cd-kulcs el lett-e használva online multiplayerre.",
      image: "http://www.retro-games.hu/images/stories/virtuemart/product/PCDVD7044.jpg",
      price: 3000,
      stock: 1,
      featured: false,
      active: true,
      onsale: false
    },
    {
      id: 27,
      catId: 1,
      name: "Carmageddon TDR 2000",
      description: "dvd tokos, Ezt Vedd Meg! kiadás, magyar feliratos borító, magyar nyelvű rövid útmutató, Sold Out kiadású CD, angol nyelvű játék. CD állapota:  enyhén karcos (hajszálkarcok), tesztelt, működik",
      image: "http://www.retro-games.hu/images/stories/virtuemart/product/PCDVD5436.jpg",
      price: 1500,
      stock: 1,
      featured: false,
      active: true,
      onsale: false
    },
    {
      id: 28,
      catId: 1,
      name: "Championship Manager 3",
      description: "dvd tokos, Sold Out kiadás, angol feliratos borító, Sold Out CD, angol nyelvű játék. CD állapota: szinte karcmentes, tesztelt, működik.",
      image: "http://www.retro-games.hu/images/stories/virtuemart/product/PCDVD7439.jpg",
      price: 1500,
      stock: 1,
      featured: true,
      active: true,
      onsale: false
    },
    {
      id: 29,
      catId: 1,
      name: "Chrome Gold Edition",
      description: "dvd tokos, EVM kiadás, magyar feliratos borító, rövid magyar nyelvű ismertető, eredeti 2 cd, magyar feliratos játék. CD-k állapota: disc1 közepesen karcos (hajszálkarcok), tesztelt, működik, disc 2 enyhén karcos (hajszálkarcok), tesztelt, működik.",
      image: "http://www.retro-games.hu/images/stories/virtuemart/product/PCDVD7630.jpg",
      price: 2000,
      stock: 1,
      featured: false,
      active: true,
      onsale: false
    },
    {
      id: 30,
      catId: 1,
      name: "Civilization: Call to Power",
      description: "dvd tokos, EVM kiadás, magyar feliratos borító, rövid magyar nyelvű ismertető, eredeti cd, angol nyelvű játék. CD állapota: szinte karcmentes, tesztelt, működik",
      image: "http://www.retro-games.hu/images/stories/virtuemart/product/PCDVD7047.jpg",
      price: 2000,
      stock: 1,
      featured: false,
      active: true,
      onsale: false
    },
    {
      id: 31,
      catId: 1,
      name: "Codename: Panzers - Phase Two",
      description: "dvd tokos, első kiadás, magyar feliratos borító, magyar nyelvű papírkézikönyv, eredeti dvd, magyar szinkronos játék. DVD állapota: enyhén karcos (hajszálkarcok), tesztelt, működik",
      image: "http://www.retro-games.hu/images/stories/virtuemart/product/PCDVD6120.jpg",
      price: 3000,
      stock: 2,
      featured: false,
      active: true,
      onsale: false
    },
    {
      id: 32,
      catId: 1,
      name: "Codename: Panzers - Phase Two",
      description: "dvd tokos, utánkiadás, magyar feliratos borító, eredeti DVD, magyar nyelvű játék. DVD állapota: enyhén-közepesen (hajszálkarcok), tesztelt, működik",
      image: "http://www.retro-games.hu/images/stories/virtuemart/product/PCDVD7050.jpg",
      price: 2000,
      stock: 1,
      featured: false,
      active: true,
      onsale: false
    },
    {
      id: 33,
      catId: 1,
      name: "Colin McRae Dirt",
      description: "dupla dvd tokos  külső kartontokban, első kiadás, magyar feliratos borító, magyar nyelvű papírkézikönyv, eredeti dvd, angol nyelvű játék. DVD állapota: szinte karcmentes, tesztelt, működik",
      image: "http://www.retro-games.hu/images/stories/virtuemart/product/PCDVD7446.jpg",
      price: 4000,
      stock: 1,
      featured: false,
      active: true,
      onsale: false
    },
    {
      id: 34,
      catId: 1,
      name: "Colin McRae Rally 2.0",
      description: "dvd tokos, utánkiadás, magyar feliratos borító, eredeti cd, angol nyelvű játék. CD állapota: karcmentes, újnak tűnik",
      image: "http://www.retro-games.hu/images/stories/virtuemart/product/PCDVD7194.jpg",
      price: 2500,
      stock: 1,
      featured: false,
      active: true,
      onsale: false
    },
    {
      id: 35,
      catId: 1,
      name: "Colin McRae Rally 2005",
      description: "dvd tokos, LV kiadás, magyar feliratos borító, magyar nyelvű papírkézikönyv, eredeti dvd, magyar szinkronos játék. DVD állapota: enyhén karcos (hajszálkarcok), tesztelt, működik.",
      image: "http://www.retro-games.hu/images/stories/virtuemart/product/PCDVD7448.jpg",
      price: 2000,
      stock: 1,
      featured: false,
      active: true,
      onsale: false
    },
    {
      id: 36,
      catId: 1,
      name: "Command & Conquer 3: Kane's Wrath kiegészítő",
      description: "dvd tokos, első kiadás, magyar feliratos borító, magyar nyelvű papírkézikönyv, eredeti dvd, magyar feliratos kiegészítő lemez, a Command & Conquer 3 alapjáték szükséges hozzá! DVD állapota: karcmentes, újnak tűnik. Hozzám használtan került, nem tudom, hogy a cd-kulcs el lett-e használva online multiplayerre.",
      image: "http://www.retro-games.hu/images/stories/virtuemart/product/PCDVD7722.jpg",
      price: 2500,
      stock: 1,
      featured: false,
      active: true,
      onsale: true
    },
    {
      id: 37,
      catId: 1,
      name: "Cossacks: European Wars",
      description: "dvd tokos, első kiadás, magyar feliratos borító, eredeti cd + kézikönyv cd, angol nyelvű játék. CD-k állapota: szinte karcmentes, tesztelt, működik",
      image: "http://www.retro-games.hu/images/stories/virtuemart/product/PCDVD7726.jpg",
      price: 2500,
      stock: 1,
      featured: false,
      active: true,
      onsale: false
    },
    {
      id: 38,
      catId: 1,
      name: "Crysis",
      description: "dvd tokos, első kiadás, magyar feliratos borító, magyar nyelvű papírkézikönyv, eredeti dvd, magyar feliratos játék. DVD állapota: karcmentes, újnak tűnik. Figyelem: A játék elindításához interneten aktiválás szükséges. Az aktiválási dátumellenőrzés nem működik már, le kell tölteni hozzá az EA oldaláról egy fájlt, hogy működjön. Az előző tulajdonos visszavonta az aktivációt, így szabadon telepíthető és használható.",
      image: "https://www.retro-games.hu/images/stories/virtuemart/product/PCDVD3359.jpg",
      price: 3000,
      stock: 3,
      featured: false,
      active: true,
      onsale: false
    },
    {
      id: 39,
      catId: 1,
      name: "Dark Messiah of Might & Magic",
      description: "dvd tokos, első kiadás, magyar feliratos borító, eredeti dvd, magyar feliratos játék. DVD állapota: enyhén karcos (hajszálkarcok), tesztelt, működik",
      image: "https://www.retro-games.hu/images/stories/virtuemart/product/PCDVD3937.jpg",
      price: 2500,
      stock: 1,
      featured: false,
      active: true,
      onsale: false
    },
    {
      id: 40,
      catId: 1,
      name: "Dead Space",
      description: "dvd tokos, első kiadás, magyar/lengyel feliratos borító, magyar/lengyel nyelvű papírkézikönyv, eredeti dvd, magyar feliratos játék. DVD állapota: karcmentes, újnak tűnik. A játék telepítéséhez internetkapcsolat és aktiválás szükséges.",
      image: "http://www.retro-games.hu/images/stories/virtuemart/product/PCDVD7450.jpg",
      price: 4000,
      stock: 1,
      featured: false,
      active: true,
      onsale: false
    },
    {
      id: 41,
      catId: 1,
      name: "Deathtrap Dungeon",
      description: "dvd tokos, EVM utánkiadás, magyar feliratos borító, magyar nyelvű útmutató, eredeti dvd, angol nyelvű játék. DVD állapota: karcmentes, újnak tűnik.",
      image: "http://www.retro-games.hu/images/stories/virtuemart/product/PCDVD7452.jpg",
      price: 2000,
      stock: 1,
      featured: false,
      active: true,
      onsale: false
    },
    {
      id: 42,
      catId: 1,
      name: "Deus Ex",
      description: "dvd tokos, Ezt Vedd Meg! kiadás, magyar feliratos borító,Sold Out kiadású CD, angol nyelvű játék. CD állapota: karcmentes, újnak tűnik",
      image: "http://www.retro-games.hu/images/stories/virtuemart/product/PCDVD4822.jpg",
      price: 2000,
      stock: 3,
      featured: false,
      active: true,
      onsale: true
    },
    {
      id: 43,
      catId: 1,
      name: "Diablo 1",
      description: "dvd tokos, BestSellers kiadás, magyar feliratos borító, eredeti cd, angol nyelvű játék. CD állapota: enyhén-közepesen karcos (hajszálkarcok), tesztelt, működik",
      image: "http://www.retro-games.hu/images/stories/virtuemart/product/PCDVD7731.jpg",
      price: 3000,
      stock: 1,
      featured: true,
      active: true,
      onsale: true
    },
    {
      id: 44,
      catId: 1,
      name: "Divine Divinity",
      description: "dvd tokos, első kiadás, angol feliratos borító,  angol nyelvű papírkézikönyv, eredeti 3cd, angol nyelvű játék. DVD állapota: installation CD 1 és 2 karcmentes, újnak tűnik. Games CD: enyhén karcos (hajszálkarcok), tesztelt, működik.",
      image: "http://www.retro-games.hu/images/stories/virtuemart/product/PCDVD7733.jpg",
      price: 2500,
      stock: 1,
      featured: false,
      active: true,
      onsale: false
    },
    {
      id: 45,
      catId: 1,
      name: "Doom 3",
      description: "dupla dvd tokos, első kiadás, angol feliratos borító, angol nyelvű papírkézikönyv, angol  nyelvű billentyűzetkiosztás, eredeti 3 cd, angol nyelvű játék. CD-k állapota: disc 1 enyhén karcos (hajszálkarcok), disc 2,3 szinte karcmentes tesztelt, működik",
      image: "http://www.retro-games.hu/images/stories/virtuemart/product/PCDVD7734.jpg",
      price: 3000,
      stock: 1,
      featured: true,
      active: true,
      onsale: false
    },
    {
      id: 46,
      catId: 1,
      name: "Empire Earth II 2 + The Art of Supremacy kiegészítő egyben (Gold Edition)",
      description: "Empire Earth II Gold Edition. dvd tokos, külső kartontokban, első kiadás, magyar feliratos borító, magyar nyelvű papírkézikönyv telepítőkóddokkal, eredeti 3 cd, magyar feliratos játék és kiegészítő. CD-k állapota: karcmentes, újnak tűnik",
      image: "http://www.retro-games.hu/images/stories/virtuemart/product/PCDVD7736.jpg",
      price: 4000,
      stock: 1,
      featured: false,
      active: true,
      onsale: false
    },
    {
      id: 47,
      catId: 1,
      name: "Fable: The Lost Chapters",
      description: "vastag dvd tokos külső kartontokban, első kiadás, magyar feliratos borító, magyar nyelvű papírkézikönyv, eredeti 4 cd, magyar feliratos játék. CD-k állapota: karcmentes, újnak tűnik",
      image: "http://www.retro-games.hu/images/stories/virtuemart/product/PCDVD7739.jpg",
      price: 4000,
      stock: 1,
      featured: false,
      active: true,
      onsale: false
    },
    {
      id: 48,
      catId: 1,
      name: "FIFA 2001",
      description: "dvd tokos, első kiadás, magyar feliratos borító, magyar nyelvű papírkézikönyv, eredeti cd, angol nyelvű játék. CD állapota: enyhén karcos (hajszálkarcok), tesztelt és működik",
      image: "http://www.retro-games.hu/images/stories/virtuemart/product/PCDVD6956.jpg",
      price: 2000,
      stock: 1,
      featured: false,
      active: true,
      onsale: false
    },
    {
      id: 49,
      catId: 1,
      name: "Football Manager 2007",
      description: "dvd tokos, első kiadás, angol feliratos borító, angol nyelvű papírkézikönyv, eredeti CD, angol nyelvű játék. CD állapota: karcmentes, újnak tűnik",
      image: "http://www.retro-games.hu/images/stories/virtuemart/product/PCDVD7479.jpg",
      price: 2500,
      stock: 1,
      featured: false,
      active: true,
      onsale: false
    },
    {
      id: 50,
      catId: 1,
      name: "Gears of War",
      description: "dvd tokos külső papírtokkal, Gyémánt kiadás, magyar feliratos borító, magyar nyelvű papírkézikönyv, magyar nyelvű illusztrált útmutató, eredeti dvd, magyar feliratos játék. DVD állapota: karcmentes, újnak tűnik",
      image: "http://www.retro-games.hu/images/stories/virtuemart/product/PCDVD7203.jpg",
      price: 3500,
      stock: 1,
      featured: false,
      active: true,
      onsale: false
    },
    {
      id: 51,
      catId: 1,
      name: "Gothic II Gold Edition (Night of the Raven is)",
      description: "Tartalma: Gothic II alapjáték és a Night of the Raven kiegészítő. DVD tokos, első kiadás, magyar/angol/cseh/szlovák feliratos borító, eredeti 4 cd, angol nyelvű játék. CD-k állapota: karcmentes, újnak tűnik",
      image: "http://www.retro-games.hu/images/stories/virtuemart/product/PCDVD6235.jpg",
      price: 3000,
      stock: 2,
      featured: false,
      active: true,
      onsale: false
    },
    {
      id: 52,
      catId: 1,
      name: "Grand Theft Auto (GTA) III 3",
      description: "dvd tokos, első kiadás, angol feliratos borító,  angol nyelvű papírkézikönyv, eredeti 2 cd, angol nyelvű játék. CD-k állapota: szinte karcmentes, tesztelt, működik",
      image: "http://www.retro-games.hu/images/stories/virtuemart/product/PCDVD7740.jpg",
      price: 3500,
      stock: 1,
      featured: true,
      active: true,
      onsale: false
    },
    {
      id: 53,
      catId: 1,
      name: "Gyűrűk Ura II: Harc Középföldéért - A boszorkánykirály felemelkedése kieg.",
      description: "dvd tokos, első kiadás, magyar feliratos borító, magyar nyelvű papírkézikönyv, eredeti dvd, angol nyelvű kiegészítő lemez, a Gyűrűk Ura II: Harc Középföldéért alapjáték kell hozzá! DVD állapota: szinte karcmentes, tesztelt, működik",
      image: "http://www.retro-games.hu/images/stories/virtuemart/product/PCDVD7745.jpg",
      price: 9000,
      stock: 1,
      featured: false,
      active: true,
      onsale: false
    },
    {
      id: 54,
      catId: 1,
      name: "Heroes of Might & Magic III 3",
      description: "dvd tokos, utánkiadás, angol feliratos borító, eredeti cd, angol nyelvű játék. CD állapota: karcmentes, újnak tűnik.",
      image: "http://www.retro-games.hu/images/stories/virtuemart/product/PCDVD7639.jpg",
      price: 2000,
      stock: 1,
      featured: false,
      active: true,
      onsale: false
    },
    {
      id: 55,
      catId: 1,
      name: "Icewind Dale II 2",
      description: "dvd tokos, első kiadás, magyar feliratos borító,  eredeti 2cd, angol nyelvű játék. CD-k állapota: enyhén karcos (hajszálkarcok), tesztelt, működik",
      image: "http://www.retro-games.hu/images/stories/virtuemart/product/PCDVD7092.jpg",
      price: 2000,
      stock: 1,
      featured: false,
      active: true,
      onsale: false
    },
    {
      id: 56,
      catId: 1,
      name: "IL-2 Sturmovik: Forgotten Battles",
      description: "dvd tokos, első kiadás, magyar feliratos borító, eredeti 2cd, magyar feliratos játék. CD-k állapota: enyhén karcos (hajszálkarcok), tesztelt, működik",
      image: "http://www.retro-games.hu/images/stories/virtuemart/product/PCDVD6884.jpg",
      price: 2000,
      stock: 1,
      featured: false,
      active: true,
      onsale: false
    },
    {
      id: 57,
      catId: 1,
      name: "Jack Keane",
      description: "dvd tokos, első kiadás, magyar feliratos borító, magyar nyelvű papírkézikönyv, eredeti dvd, magyar feliratos játék. CD állapota: szinte karcmentes, tesztelt, működik",
      image: "http://www.retro-games.hu/images/stories/virtuemart/product/PCDVD7503.jpg",
      price: 2000,
      stock: 1,
      featured: false,
      active: true,
      onsale: true
    },
    {
      id: 58,
      catId: 1,
      name: "Ki vagy rúgva!",
      description: "dvd tokos, első kiadás, magyar feliratos borító, eredeti cd, magyar feliratos játék. CD állapota: karcmentes, újnak tűnik",
      image: "http://www.retro-games.hu/images/stories/virtuemart/product/PCDVD7504.jpg",
      price: 2500,
      stock: 2,
      featured: false,
      active: true,
      onsale: false
    },
    {
      id: 59,
      catId: 1,
      name: "Lara Croft Tomb Raider Legend",
      description: "dvd tokos, első kiadás, magyar feliratos borító, eredeti dvd, angol nyelvű játék. DVD állapota: enyhén karcos (hajszálkarcok), tesztelt, működik",
      image: "http://www.retro-games.hu/images/stories/virtuemart/product/PCDVD6281.jpg",
      price: 2000,
      stock: 1,
      featured: false,
      active: true,
      onsale: false
    },
    {
      id: 60,
      catId: 1,
      name: "Leisure Suit Larry 7: Love For Sail!",
      description: "dvd tokos, Sikersorozat kiadás, magyar feliratos borító, eredeti cd, angol nyelvű játék. CD állapota: karcmentes, újnak tűnik",
      image: "http://www.retro-games.hu/images/stories/virtuemart/product/PCDVD5460.jpg",
      price: 2000,
      stock: 1,
      featured: false,
      active: true,
      onsale: false
    },
    {
      id: 61,
      catId: 1,
      name: "Mafia",
      description: "dvd tokos, első kiadás, magyar feliratos borító, eredeti 3cd, angol nyelvű játék. CD-k állapota: közepesen karcos (hajszálkarcok), tesztelt, működik",
      image: "http://www.retro-games.hu/images/stories/virtuemart/product/PCDVD7754.jpg",
      price: 3000,
      stock: 1,
      featured: false,
      active: true,
      onsale: false
    },
    {
      id: 62,
      catId: 1,
      name: "Medal of Honor: Allied Assault Warchest (alapjáték + Spearhead + Breakthrough)",
      description: "dvd tokos, első kiadás, magyar/cseh feliratos borító, magyar/cseh nyelvű papírkézikönyv, eredeti 4cd, angol nyelvű játékok. A kollekció tartalma: Medal Of Honor Allied Assault, Medal Of Honor Allied Assault: Spearhead kiegészítő lemez, Medal Of Honor Allied Assault: Breakthrough kiegészítő lemez. CD-k állapota: enyhén karcos (hajszálkarcok), tesztelt, működik",
      image: "http://www.retro-games.hu/images/stories/virtuemart/product/PCDVD7516.jpg",
      price: 3000,
      stock: 1,
      featured: false,
      active: true,
      onsale: false
    },
    {
      id: 63,
      catId: 1,
      name: "Medieval II 2: Total War Gold Edition (Kingdoms is)",
      description: "Kollekció: tartalmazza az alapjátékot és a Kingdoms kiegészítőt. dvd tokos külső papírtokkal, Gyémánt kiadás, magyar feliratos borító, magyar nyelvű papírkézikönyv, eredeti 2 dvd, magyar feliratos játék. DVD-k állapota: karcmentes, újnak tűnik",
      image: "http://www.retro-games.hu/images/stories/virtuemart/product/PCDVD7761.jpg",
      price: 3500,
      stock: 1,
      featured: false,
      active: true,
      onsale: false
    },
    {
      id: 64,
      catId: 1,
      name: "Might & Magic VI: The Mandate of Heaven",
      description: "dvd tokos, EVM utánkiadás, magyar feliratos borító,  rövid magyar nyelvű ismertető, eredeti 2 cd, angol nyelvű játék. CD-k állapota: szinte karcmentes, tesztelt, működik",
      image: "http://www.retro-games.hu/images/stories/virtuemart/product/PCDVD7521.jpg",
      price: 2000,
      stock: 1,
      featured: false,
      active: true,
      onsale: false
    },
    {
      id: 65,
      catId: 1,
      name: "Myst IV: Revelation",
      description: "dvd tokos, első kiadás, magyar feliratos borító, magyar nyelvű papírkézikönyv, eredeti 2 DVD, magyar feliratos játék. DVD-k állapota: enyhén karcos (hajszálkarcok), tesztelt, működik",
      image: "http://www.retro-games.hu/images/stories/virtuemart/product/PCDVD7763.jpg",
      price: 4000,
      stock: 1,
      featured: false,
      active: true,
      onsale: false
    },
    {
      id: 66,
      catId: 1,
      name: "Need for Speed Carbon",
      description: "dvd tokos, első kiadás, magyar feliratos borító, magyar nyelvű papírkézikönyv, eredeti dvd, magyar feliratos játék. DVD állapota: közepesen karcos (hajszálkarcok), tesztelt, működik.",
      image: "http://www.retro-games.hu/images/stories/virtuemart/product/PCDVD7764.jpg",
      price: 3000,
      stock: 1,
      featured: false,
      active: true,
      onsale: false
    },
    {
      id: 67,
      catId: 1,
      name: "Neverwinter Nights Diamond Edition",
      description: "dvd tokos, kollekció, angol/magyar/cseh/szlovák feliratos borító, eredeti 5 cd + 1 dvd, ebből az egyik a manual cd, angol nyelvű játékok. Ennek a kiadásnak a tartalma: Neverwinter Nights alapjáték, Shadows of Undrentide kiegészítő lemez, Hordes of the Underdark kiegészítő lemez, Kingmaker kiegészítő lemez, ez utóbbiban van a Kingmaker, Shadowguard és Witch's Wake modul is. CD-k állapota: karcmentes, újnak tűnik",
      image: "http://www.retro-games.hu/images/stories/virtuemart/product/PCDVD6462.jpg",
      price: 4500,
      stock: 1,
      featured: false,
      active: true,
      onsale: false
    },
    {
      id: 68,
      catId: 1,
      name: "Pharaoh",
      description: "dvd tokos, utánkiadás, angol feliratos borító, eredeti cd, angol nyelvű játék. CD állapota: enyhén karcos (hajszálkarcok), tesztelt, működik",
      image: "http://www.retro-games.hu/images/stories/virtuemart/product/PCDVD7663.jpg",
      price: 1500,
      stock: 1,
      featured: false,
      active: true,
      onsale: false
    },
    {
      id: 69,
      catId: 1,
      name: "Quake 4",
      description: "dvd tokos, Best Of Activision kiadás, angol feliratos borító, angol nyelvű papírkézikönyv, eredeti dvd, angol nyelvű játék. DVD állapota: enyhén-közepesen karcos (hajszálkarcok), tesztelt, működik",
      image: "http://www.retro-games.hu/images/stories/virtuemart/product/PCDVD7776.jpg",
      price: 2500,
      stock: 1,
      featured: false,
      active: true,
      onsale: false
    },
    {
      id: 70,
      catId: 1,
      name: "Resident Evil 3: Nemesis",
      description: "dvd tokos, EVM utánkiadás, magyar feliratos borító, eredeti cd, angol nyelvű játék. CD állapota: karcmentes, újnak tűnik.",
      image: "http://www.retro-games.hu/images/stories/virtuemart/product/PCDVD7780.jpg",
      price: 2500,
      stock: 1,
      featured: false,
      active: true,
      onsale: true
    },
    {
      id: 71,
      catId: 1,
      name: "Rome Total War Antológia (alapjáték + Barbarian Invasion + Alexander)",
      description: "kollekció (Rome Total War és mindkét kiegészítője, az Alexander és a Barbarian Invasion), LV kiadás, magyar feliratos borító, magyar nyelvű vastag papírkézikönyv, eredeti dvd, magyar feliratos játék. DVD állapota: karcmentes, újnak tűnik",
      image: "http://www.retro-games.hu/images/stories/virtuemart/product/PCDVD7783.jpg",
      price: 3500,
      stock: 1,
      featured: true,
      active: true,
      onsale: false
    },
    {
      id: 72,
      catId: 1,
      name: "Sacred",
      description: "dvd tokos, első kiadás, magyar feliratos borító, magyar nyelvű papírkézikönyv, térkép, eredeti 2cd, angol nyelvű játék. CD-k állapota: enyhén karcos (hajszálkarcok), tesztelt, működik",
      image: "http://www.retro-games.hu/images/stories/virtuemart/product/PCDVD7784.jpg",
      price: 3000,
      stock: 1,
      featured: false,
      active: true,
      onsale: false
    },
    {
      id: 73,
      catId: 1,
      name: "Sherlock Holmes: The Awakened",
      description: "dvd tokos, EVM kiadás, magyar feliratos borító, rövid magyar nyelvű ismertető, eredeti DVD, magyar feliratos játék. DVD állapota: karcmentes, újnak tűnik",
      image: "http://www.retro-games.hu/images/stories/virtuemart/product/PCDVD5361.jpg",
      price: 2000,
      stock: 1,
      featured: false,
      active: true,
      onsale: false
    },
    {
      id: 74,
      catId: 1,
      name: "SimCity Sim City 4 Deluxe Edition (Rush Hour)",
      description: "dvd tokos, EA Classics kiadás, magyar/cseh feliratos borító, eredeti 2 cd, angol nyelvű játék. Tartalmazza az alapjátékot és a Rush Hour kiegészítőt. CD-k állapota: enyhén karcos (hajszálkarcok), tesztelt, működik",
      image: "http://www.retro-games.hu/images/stories/virtuemart/product/PCDVD7022.jpg",
      price: 2500,
      stock: 1,
      featured: false,
      active: true,
      onsale: false
    },
    {
      id: 75,
      catId: 1,
      name: "Spellforce 1 Platinum (The Order of Dawn + The Breath of Winter és Shadow of the Phoenix kiege",
      description: "dvd tokos, első kiadás, magyar/angol/cseh/szlovák feliratos borító, eredeti dvd, angol nyelvű kollekció: The Order of Dawn alapjáték + The Breath of Winter és Shadow of the Phoenix kiegészítők. DVD állapota: enyhén karcos (hajszálkarcok), tesztelt, működik",
      image: "https://www.retro-games.hu/images/stories/virtuemart/product/PCDVD2672.jpg",
      price: 2500,
      stock: 1,
      featured: false,
      active: true,
      onsale: false
    },
    {
      id: 76,
      catId: 1,
      name: "Star Wars Jedi Knight II: Jedi Outcast",
      description: "dvd tokos, első kiadás, angol feliratos borító, angol nyelvű papírkézikönyv, eredeti cd, angol nyelvű játék. CD állapota:  karcmentes, újnak tűnik",
      image: "http://www.retro-games.hu/images/stories/virtuemart/product/PCDVD7798.jpg",
      price: 3000,
      stock: 1,
      featured: true,
      active: true,
      onsale: false
    },
    {
      id: 77,
      catId: 1,
      name: "The Elder Scrolls III: Morrowind + Tribunal + Bloodmoon (Game of the Year kiadás)",
      description: "dvd tokos, Az év játéka kiadás, magyar feliratos borító, magyar nyelvű papírkézikönyv, eredeti 4 cd, angol nyelvű játék; tartalmazza az alapjátékot (Morrowind), a két kiegészítőt (Tribunal, Bloodmoon), valamint a TES Construction Setet. CD-k állapota: karcmentes, újnak tűnik",
      image: "http://www.retro-games.hu/images/stories/virtuemart/product/PCDVD6580.jpg",
      price: 4000,
      stock: 1,
      featured: false,
      active: true,
      onsale: false
    },
    {
      id: 78,
      catId: 1,
      name: "The Settlers II 2 10th Anniversary Edition",
      description: "dvd tokos, Ubisoft Exclusive kiadás, magyar feliratos borító, eredeti cd, angol nyelvű játék. CD állapota: karcmentes, újnak tűnik",
      image: "http://www.retro-games.hu/images/stories/virtuemart/product/PCDVD7127.jpg",
      price: 2000,
      stock: 1,
      featured: false,
      active: true,
      onsale: false
    },
    {
      id: 79,
      catId: 1,
      name: "The Sims 2 alapjáték",
      description: "dvd tokos, első kiadás, magyar feliratos borító, magyar nyelvű papírkézikönyv, eredeti dvd, magyar feliratos játék. DVD állapota: enyhén karcos (hajszálkarcok), tesztelt, működik.",
      image: "http://www.retro-games.hu/images/stories/virtuemart/product/PCDVD7811.jpg",
      price: 2500,
      stock: 1,
      featured: false,
      active: true,
      onsale: false
    },
    {
      id: 80,
      catId: 1,
      name: "Theocracy",
      description: "dvd tokos, utánkiadás, magyar feliratos borító, eredeti 2cd, angol nyelvű játék. CD-k állapota: enyhén karcos (hajszálkarcok), tesztelt, működik",
      image: "http://www.retro-games.hu/images/stories/virtuemart/product/PCDVD7165.jpg",
      price: 3500,
      stock: 3,
      featured: false,
      active: true,
      onsale: false
    },
    {
      id: 81,
      catId: 1,
      name: "Tomb Raider II 2: Starring Lara Croft",
      description: "dvd tokos, EVM utánkiadás, magyar feliratos borító, eredeti cd, angol nyelvű játék. CD állapota: szinte karcmentes, tesztelt, működik.",
      image: "http://www.retro-games.hu/images/stories/virtuemart/product/PCDVD7599.jpg",
      price: 1500,
      stock: 2,
      featured: false,
      active: true,
      onsale: false
    },
    {
      id: 82,
      catId: 1,
      name: "Unreal Tournament III",
      description: "dvd tokos kartonpapír-tokban, első kiadás, magyar feliratos borító, magyar nyelvű papírkézikönyv, art book, eredeti dvd, magyar nyelvű játék. DVD állapota: karcmentes, újnak tűnik",
      image: "https://www.retro-games.hu/images/stories/virtuemart/product/PCDVD3502.jpg",
      price: 2500,
      stock: 4,
      featured: false,
      active: true,
      onsale: false
    },
    {
      id: 83,
      catId: 1,
      name: "Warcraft III: Frozen Throne (német)",
      description: "dvd tokos, első kiadás, német feliratos borító, német nyelvű papírkézikönyv, eredeti cd, német nyelvű kiegészítő lemez, futtatásához szükséges a Warcraft III alapjáték! CD állapota: karcmentes, újnak tűnik",
      image: "http://www.retro-games.hu/images/stories/virtuemart/product/PCDVD6108.jpg",
      price: 2500,
      stock: 1,
      featured: false,
      active: true,
      onsale: false
    },
    {
      id: 84,
      catId: 1,
      name: "Wizardry 8",
      description: "dvd tokos, első kiadás, magyar feliratos borító, magyar nyelvű papírkézikönyv, eredeti 3cd, angol nyelvű játék. CD-k állapota: karcmentes, újnak tűnik",
      image: "http://www.retro-games.hu/images/stories/virtuemart/product/PCDVD7180.jpg",
      price: 4000,
      stock: 1,
      featured: false,
      active: true,
      onsale: false
    },
    {
      id: 85,
      catId: 1,
      name: "Alan Wake's American Nightmare (új)",
      description: "dvd tokos, első kiadás, angol feliratos borító, eredeti dvd, angol nyelvű játék. Új, bontatlan, fóliás. Figyelem: telepítéshez internetkapcsolat és ingyenes Steam fiók szükséges.",
      image: "http://www.retro-games.hu/images/stories/virtuemart/product/PCDVD6469.jpg",
      price: 3500,
      stock: 1,
      featured: false,
      active: true,
      onsale: false
    },
    {
      id: 86,
      catId: 1,
      name: "Call of Juarez: Bound in Blood (új)",
      description: "dvd tokos, Ubisoft Exclusive kiadás, magyar feliratos borító, magyar nyelvű papírkézikönyv, eredeti dvd, angol nyelvű játék. Új, bontatlan, fóliás.",
      image: "http://www.retro-games.hu/images/stories/virtuemart/product/PCDVD6187.jpg",
      price: 3500,
      stock: 1,
      featured: false,
      active: true,
      onsale: false
    },
    {
      id: 87,
      catId: 1,
      name: "Chris Sawyer's Locomotion (új)",
      description: "dvd tokos, első kiadás, angol feliratos borító, angol nyelvű papírkézikönyv, eredeti cd, angol nyelvű játék. Új, bontatlan, fóliás!",
      image: "http://www.retro-games.hu/images/stories/virtuemart/product/PCDVD7192.jpg",
      price: 3500,
      stock: 1,
      featured: false,
      active: true,
      onsale: false
    },
    {
      id: 88,
      catId: 1,
      name: "Civilization IV: Extended Complete Edition (Warlords + Beyond the Sword + Colonization) (új)",
      description: "kollekció, a Civilization IV alapjátékot és annak mindkét kiegészítőjét, és a Colonizationt is tartalmazza. dvd tokos, Premium Games kiadás, magyar feliratos borító,  magyar nyelvű papírkézikönyv, technológiai fa, eredeti 2 dvd, angol nyelvű játékok. Új, bontatlan, fóliás!",
      image: "http://www.retro-games.hu/images/stories/virtuemart/product/PCDVD7321.jpg",
      price: 4500,
      stock: 1,
      featured: false,
      active: true,
      onsale: false
    },
    {
      id: 89,
      catId: 1,
      name: "Command & Conquer: Red Alert 3 - Uprising (új)",
      description: "dvd tokos, első kiadás, lengyel/cseh/magyar feliratos borító, angol nyelvű kiegészítő (a Red Alert 3 alapjáték szükséges hozzá). A doboz kizárólag egyszer használatos letöltő kódot tartalmaz, amelyet online aktiválni kell, lemezt nem. Új, bontatlan, fóliás!",
      image: "http://www.retro-games.hu/images/stories/virtuemart/product/PCDVD7616.jpg",
      price: 1500,
      stock: 1,
      featured: false,
      active: true,
      onsale: false
    },
    {
      id: 90,
      catId: 1,
      name: "Commandos Ultimate Anthology (1 + 2 + 3 + Strike Force) (új)",
      description: "kollekció, dvd tokos, Gamemania kiadás, magyar feliratos borító, magyar nyelvű rövid útmutató, eredeti dvd, angol nyelvű játékok. Tartalma: Commandos és kiegészítője (Behind Enemy Line, Beyond the Call of Duty), Commandos 2: Men of Courage, Commandos 3: Destination Berlin, Commandos Strike Force. Új, bontatlan, fóliás!",
      image: "http://www.retro-games.hu/images/stories/virtuemart/product/PCDVD7289.jpg",
      price: 4000,
      stock: 3,
      featured: false,
      active: true,
      onsale: false
    },
    {
      id: 91,
      catId: 1,
      name: "Dishonored (új)",
      description: "dvd tokos, Classics Collection kiadás, magyar/cseh/lengyel nyelvű borító, magyar feliratos játék. Új, bontatlan, fóliás! Figyelem: ingyenes Steam fiók és internetes aktiválás szükséges a használatához.",
      image: "http://www.retro-games.hu/images/stories/virtuemart/product/PCDVD7295.jpg",
      price: 2500,
      stock: 2,
      featured: false,
      active: true,
      onsale: false
    },
    {
      id: 92,
      catId: 1,
      name: "Divinity II: Ego Draconis (új)",
      description: "dvd tokos, első kiadás, angol feliratos borító, angol nyelvű papírkézikönyv, eredeti dvd, angol nyelvű játék.Új, bontatlan, fóliás!",
      image: "http://www.retro-games.hu/images/stories/virtuemart/product/PCDVD7296.jpg",
      price: 6000,
      stock: 2,
      featured: true,
      active: true,
      onsale: false
    },
    {
      id: 93,
      catId: 1,
      name: "Fallout 3 Game of the Year Edition (GOTY, összes DLC) (új)",
      description: "Kollekció, tartalma: Fallout 3 alapjáték + 5 DLC. Premium Games kiadás, magyar feliratos borító, magyar nyelvű rövid útmutató, eredeti dvd, magyar feliratos játék.Új, bontatlan, fóliás! Fontos: Interneten aktiválni kell a játékot, a mentéshez Windows Live fiók kell, de az lehet offline is.",
      image: "http://www.retro-games.hu/images/stories/virtuemart/product/PCDVD7299.jpg",
      price: 3500,
      stock: 1,
      featured: false,
      active: true,
      onsale: true
    },
    {
      id: 94,
      catId: 1,
      name: "Grand Theft Auto GTA Vice City (új)",
      description: "dvd tokos, Gamemania kiadás, magyar feliratos borító, magyar nyelvű rövid útmutató, eredeti dvd, angol nyelvű játék.Új, bontatlan, fóliás!",
      image: "http://www.retro-games.hu/images/stories/virtuemart/product/PCDVD7402.jpg",
      price: 3000,
      stock: 1,
      featured: false,
      active: true,
      onsale: false
    },
    {
      id: 95,
      catId: 1,
      name: "Icewind Dale Enhanced Edition (új)",
      description: "dvd tokos, Classics Collection kiadás, magyar/cseh/lengyel borító, angol nyelvű játék. Tartalmazza a Heart of Winter és a Trials of the Luremaster kiegészítőket is. Új, bontatlan, fóliás!",
      image: "http://www.retro-games.hu/images/stories/virtuemart/product/PCDVD6671.jpg",
      price: 2500,
      stock: 1,
      featured: false,
      active: true,
      onsale: false
    },
    {
      id: 96,
      catId: 1,
      name: "King's Bounty: Armored Princess (új) (angol)",
      description: "dvd tokos, Gamemania kiadás, rövid magyar nyelvű útmutató, magyar feliratos borító, eredeti dvd, angol nyelvű játék. Új, bontatlan, fóliás!",
      image: "http://www.retro-games.hu/images/stories/virtuemart/product/PCDVD7405.jpg",
      price: 3000,
      stock: 3,
      featured: false,
      active: true,
      onsale: false
    },
    {
      id: 97,
      catId: 1,
      name: "Mass Effect (új)",
      description: "dvd tokos, LV utánkiadás, magyar nyelvű papírkézikönyv, magyar feliratos borító, magyar feliratos játék. Új, bontatlan, fóliás!",
      image: "http://www.retro-games.hu/images/stories/virtuemart/product/PCDVD7615.jpg",
      price: 3000,
      stock: 1,
      featured: false,
      active: true,
      onsale: true
    },
    {
      id: 98,
      catId: 1,
      name: "Microsoft Flight Simulator X Deluxe (új)",
      description: "dvd tokos, első kiadás, angol feliratos borító, angol nyelvű papírkézikönyv, eredeti DVD, angol nyelvű játék. Új, bontatlan, fóliás!",
      image: "http://www.retro-games.hu/images/stories/virtuemart/product/PCDVD7012.jpg",
      price: 22000,
      stock: 1,
      featured: false,
      active: true,
      onsale: false
    },
    {
      id: 99,
      catId: 1,
      name: "Pokoli szomszédok: Oroszországból szeretettel (új)",
      description: "dvd tokos, első kiadás, magyar feliratos borító, rövid magyar nyelvű ismertető, eredeti cd, magyar feliratos játék. Új, bontatlan, fóliás!",
      image: "http://www.retro-games.hu/images/stories/virtuemart/product/PCDVD5323.jpg",
      price: 1500,
      stock: 16,
      featured: false,
      active: true,
      onsale: true
    },
    {
      id: 100,
      catId: 1,
      name: "Risen 3: Titan Lords (új)",
      description: "dvd tokos, Premium Games kiadás, magyar feliratos borító, magyar nyelvű rövid útmutató, eredeti dvd, angol nyelvű játék. Figyelem: ingyenes Steam fiók és internetes aktiválás szükséges a használatához.",
      image: "http://www.retro-games.hu/images/stories/virtuemart/product/PCDVD7318.jpg",
      price: 3000,
      stock: 1,
      featured: false,
      active: true,
      onsale: false
    },
    {
      id: 101,
      catId: 1,
      name: "Spellforce 2: Faith of Destiny (új)",
      description: "dvd tokos, első kiadás, angol feliratos borító, eredeti dvd, angol nyelvű játék. Új, bontatlan, fóliás.",
      image: "http://www.retro-games.hu/images/stories/virtuemart/product/PCDVD6491.jpg",
      price: 3000,
      stock: 1,
      featured: false,
      active: true,
      onsale: false
    },
    {
      id: 102,
      catId: 1,
      name: "Star Wars: The Clone Wars - Republic Heroes (új)",
      description: "dvd tokos, első kiadás kiadás, angol feliratos borító, angol nyelvű papírkézikönyv, eredeti dvd, angol nyelvű játék. Új, bontatlan, fóliás!",
      image: "https://www.retro-games.hu/images/stories/virtuemart/product/PCDVD3686.jpg",
      price: 3000,
      stock: 1,
      featured: false,
      active: true,
      onsale: false
    },
    {
      id: 103,
      catId: 1,
      name: "Stronghold 2 Deluxe (új)",
      description: "dvd tokos, Gamemania kiadás, magyar feliratos borító, magyar nyelvű rövid papírkézikönyv, eredeti dvd, angol nyelvű játék. Új, bontatlan, fóliás!",
      image: "http://www.retro-games.hu/images/stories/virtuemart/product/PCDVD7323.jpg",
      price: 2500,
      stock: 2,
      featured: false,
      active: true,
      onsale: false
    },
    {
      id: 104,
      catId: 1,
      name: "The Elder Scrolls 4 IV: Oblivion + Knights of the Nine + Shivering Isles (új)",
      description: "Game of the Year Edition. Tartalma: alapjáték + Knights of the Nine és Shivering Isles kiegészítők. Classics Collection kiadás, magyar/cseh/lengyel nyelvű borító, angol nyelvű játék. Új, bontatlan, fóliás!",
      image: "http://www.retro-games.hu/images/stories/virtuemart/product/PCDVD7298.jpg",
      price: 2500,
      stock: 2,
      featured: false,
      active: true,
      onsale: false
    },
    {
      id: 105,
      catId: 1,
      name: "Tom Clancy's Splinter Cell (új)",
      description: "dvd tokos, első kiadás, magyar feliratos borító, eredeti dvd, angol nyelvű játék. Új, bontatlan, fóliás.",
      image: "http://www.retro-games.hu/images/stories/virtuemart/product/PCDVD6496.jpg",
      price: 4000,
      stock: 1,
      featured: false,
      active: true,
      onsale: false
    },
    {
      id: 106,
      catId: 1,
      name: "Two Worlds (új)",
      description: "dvd tokos, első kiadás, magyar feliratos borító, magyar nyelvű papírkézikönyv, eredeti dvd, angol nyelvű játék. Új, bontatlan, fóliás! Első használat előtt interneten aktiválni szükséges.",
      image: "http://www.retro-games.hu/images/stories/virtuemart/product/PCDVD5334.jpg",
      price: 2000,
      stock: 6,
      featured: false,
      active: true,
      onsale: false
    },
    {
      id: 107,
      catId: 1,
      name: "XCOM: Enemy Unknown Complete Edition (Enemy Within is) (új)",
      description: "dvd tokos, Gamemania kiadás, magyar/cseh/lengyel feliratos borító, magyar nyelvű rövid ismertető, eredeti dvd, angol nyelvű játék. Új, bontatlan, fóliás! Használatához Steam fiók és online aktiválás szükséges.",
      image: "http://www.retro-games.hu/images/stories/virtuemart/product/PCDVD7330.jpg",
      price: 2500,
      stock: 1,
      featured: false,
      active: true,
      onsale: false
    },
    {
      id: 108,
      catId: 0,
      name: "12 O'Clock High: Bombing the Reich",
      description: "papírdobozos, első kiadás, angol feliratos papírdobozos, angol nyelvű papírkézikönyv, cd tokban az eredeti cd, angol nyelvű játék",
      image: "https://www.retro-games.hu/images/stories/virtuemart/product/PCENB0002.jpg",
      price: 6000,
      stock: 1,
      featured: false,
      active: true,
      onsale: false
    },
    {
      id: 109,
      catId: 0,
      name: "Activision's Atari 2600 Action Pack 2",
      description: "papírdobozos, kollekció, angol feliratos papírdobozos, angol nyelvű papírkézikönyv a cd tokban, cd tokban az eredeti cd, angol nyelvű játékok. A kollekció 15db Atari 2600 játékot tartalmaz: Atlantis, Barnstorming, Dolphin, Dragster, Enduro, Ice Hockey, Keystone Kapers, LAser Blast, Megamania, Oink!, Plaque Attack, River Raid II, Skiing, Stampede, Tennis",
      image: "https://www.retro-games.hu/images/stories/virtuemart/product/PCENB0012.jpg",
      price: 4000,
      stock: 1,
      featured: false,
      active: true,
      onsale: false
    },
    {
      id: 110,
      catId: 0,
      name: "Archipelagos",
      description: "papírdobozos, első kiadás, angol feliratos papírdobozos, segédanyag, 1db 3,5 floppy, angol nyelvű játék",
      image: "https://www.retro-games.hu/images/stories/virtuemart/product/PCENB0023.jpg",
      price: 5000,
      stock: 1,
      featured: false,
      active: true,
      onsale: false
    },
    {
      id: 111,
      catId: 0,
      name: "Armor Command",
      description: "papírdobozos, első kiadás, angol feliratos papírdobozos, angol nyelvű papírkézikönyv, reference guide, cd tokban az eredeti cd, angol nyelvű játék",
      image: "https://www.retro-games.hu/images/stories/virtuemart/product/PCENB0024.jpg",
      price: 4000,
      stock: 1,
      featured: false,
      active: true,
      onsale: false
    },
    {
      id: 112,
      catId: 0,
      name: "Cyberstorm 2: Corporate Wars",
      description: "papírdobozos, első kiadás, USA kiadás, speciális kihajtható előlapos angol feliratos papírdobozos, angol nyelvű papírkézikönyv, billentyűzet kiosztás, cd tokban az eredeti cd, angol nyelvű játék",
      image: "https://www.retro-games.hu/images/stories/virtuemart/product/PCENB0069.jpg",
      price: 4000,
      stock: 1,
      featured: false,
      active: true,
      onsale: false
    },
    {
      id: 113,
      catId: 0,
      name: "Dagger's Rage",
      description: "papírdobozos, első kiadás, angol feliratos papírdobozos, angol nyelvű papírkézikönyv, technical guide, német nyelvű papírkézikönyv, technical guide, regisztrációs kártya, kitámasztó szivacs, cd tokban az eredeti cd, angol nyelvű játék",
      image: "https://www.retro-games.hu/images/stories/virtuemart/product/PCENB0070.jpg",
      price: 5000,
      stock: 1,
      featured: false,
      active: true,
      onsale: false
    },
    {
      id: 114,
      catId: 0,
      name: "Dark Reign 2",
      description: "papírdobozos, első kiadás, angol feliratos papírdobozos, angol nyelvű papírkézikönyv, regisztrációs kártya, cd tokban az eredeti cd, angol nyelvű játék",
      image: "https://www.retro-games.hu/images/stories/virtuemart/product/PCENB0073.jpg",
      price: 4000,
      stock: 1,
      featured: false,
      active: true,
      onsale: false
    },
    {
      id: 115,
      catId: 0,
      name: "Dominant Species",
      description: "papírdobozos, első kiadás, angol feliratos papírdobozos, angol nyelvű papírkézikönyv, regisztrációs kártya, cd tokban az eredeti cd, angol nyelvű játék",
      image: "https://www.retro-games.hu/images/stories/virtuemart/product/PCENB0079.jpg",
      price: 5000,
      stock: 1,
      featured: false,
      active: true,
      onsale: true
    },
    {
      id: 116,
      catId: 0,
      name: "Dogs Of War",
      description: "papírdobozos, első kiadás, angol feliratos papírdobozos, angol nyelvű papírkézikönyv, regisztrációs kártya, cd tokban az eredeti cd, angol nyelvű játék",
      image: "https://www.retro-games.hu/images/stories/virtuemart/product/PCENB0081.jpg",
      price: 4000,
      stock: 1,
      featured: false,
      active: true,
      onsale: false
    },
    {
      id: 117,
      catId: 0,
      name: "CyberRace",
      description: "papírdobozos, Big Games kiadás, olasz feliratos speciális alakú papírdobozos, olasz nyelvű papírkézikönyv, cd tokban az eredeti cd, angol nyelvű játék",
      image: "https://www.retro-games.hu/images/stories/virtuemart/product/PCENB0084.jpg",
      price: 3000,
      stock: 1,
      featured: false,
      active: true,
      onsale: false
    },
    {
      id: 118,
      catId: 0,
      name: "England: Championship Special",
      description: "papírdobozos, első kiadás, angol/német/francia/olasz feliratos papírdobozos, angol/német/francia/olasz nyelvű papírkézikönyv, 2db 5,25 floppy, angol nyelvű játék",
      image: "https://www.retro-games.hu/images/stories/virtuemart/product/PCENB0091.jpg",
      price: 3000,
      stock: 1,
      featured: false,
      active: true,
      onsale: false
    },
    {
      id: 119,
      catId: 0,
      name: "F-16 Combat Pilot",
      description: "papírdobozos, első kiadás, angol feliratos papírdobozos, angol nyelvű papírkézikönyv, 2db 3,5 floppy, angol nyelvű játék",
      image: "https://www.retro-games.hu/images/stories/virtuemart/product/PCENB0095.jpg",
      price: 5000,
      stock: 1,
      featured: false,
      active: true,
      onsale: false
    },
    {
      id: 120,
      catId: 0,
      name: "Fighter Squadron",
      description: "papírdobozos, első kiadás, angol feliratos papírdobozos, angol nyelvű papírkézikönyv, billentyűzet kiosztás, cd tokban az eredeti cd, angol nyelvű játék",
      image: "https://www.retro-games.hu/images/stories/virtuemart/product/PCENB0102.jpg",
      price: 5000,
      stock: 1,
      featured: false,
      active: true,
      onsale: false
    },
    {
      id: 121,
      catId: 0,
      name: "Flight Unlimited II",
      description: "papírdobozos, Premier Collection kiadás, angol/német/francia feliratos papírdobozos, angol nyelvű billentyűzet kiosztás, kihajtható papírtérkép, cd tokban az eredeti 2cd, angol nyelvű játék",
      image: "https://www.retro-games.hu/images/stories/virtuemart/product/PCENB0105.jpg",
      price: 3500,
      stock: 1,
      featured: false,
      active: true,
      onsale: false
    },
    {
      id: 122,
      catId: 0,
      name: "Formula 1 97",
      description: "papírdobozos, első kiadás, angol feliratos papírdobozos, angol nyelvű papírkézikönyv, cd tokban az eredeti cd, angol nyelvű játék. Psygnosis!",
      image: "https://www.retro-games.hu/images/stories/virtuemart/product/PCENB0109.jpg",
      price: 4000,
      stock: 1,
      featured: false,
      active: true,
      onsale: false
    },
    {
      id: 123,
      catId: 0,
      name: "Formula 1 Championship Edition",
      description: "papírdobozos, első kiadás, angol feliratos papírdobozos, angol nyelvű papírkézikönyv a cd tokban, cd tokban az eredeti cd, angol nyelvű játék. Psygnosis!",
      image: "https://www.retro-games.hu/images/stories/virtuemart/product/PCENB0110.jpg",
      price: 5000,
      stock: 1,
      featured: false,
      active: true,
      onsale: false
    },
    {
      id: 124,
      catId: 0,
      name: "The French Open Paris 1998",
      description: "papírdobozos, első kiadás, angol feliratos papírdobozos, cd tokban az eredeti cd, angol nyelvű játék. Bontatlan a papírdobozon belüli cd tok!",
      image: "https://www.retro-games.hu/images/stories/virtuemart/product/PCENB0111.jpg",
      price: 4000,
      stock: 1,
      featured: false,
      active: true,
      onsale: false
    },
    {
      id: 125,
      catId: 0,
      name: "Heist",
      description: "papírdobozos, első kiadás, angol feliratos papírdoboz, cd tokban az eredeti cd, angol nyelvű játék",
      image: "https://www.retro-games.hu/images/stories/virtuemart/product/PCENB0130.jpg",
      price: 5000,
      stock: 1,
      featured: false,
      active: true,
      onsale: false
    },
    {
      id: 126,
      catId: 0,
      name: "Indy Car Racing Circuits Expansion Pa",
      description: "papírdobozos, első kiadás, angol/német/francia feliratos papírdobozos, angol/námet/francia nyelvű papírkézikönyv, 2db 3,5 floppy, angol nyelvű játék. Futtatásához szükséges az Indy Car alapjáték!",
      image: "https://www.retro-games.hu/images/stories/virtuemart/product/PCENB0141.jpg",
      price: 4000,
      stock: 1,
      featured: false,
      active: true,
      onsale: false
    },
    {
      id: 127,
      catId: 0,
      name: "KA52 Team Alligator",
      description: "papírdobozos, első kiadás, angol feliratos papírdoboz, angol nyelvű papírkézikönyv, billentyűzet kiosztás, cd tokban az eredeti cd, angol nyelvű játék. A papírdoboz alsó részén van egy kisebb sérülés",
      image: "https://www.retro-games.hu/images/stories/virtuemart/product/PCENB0147.jpg",
      price: 3500,
      stock: 1,
      featured: false,
      active: true,
      onsale: true
    },
    {
      id: 128,
      catId: 0,
      name: "Maelstrom: The Ultimate Galactic Strategy G.",
      description: "papírdobozos, első kiadás, USA kiadás, angol feliratos papírdoboz, angol nyelvű papírkézikönyv, 6db 3,5 floppy, angol nyelvű játék",
      image: "https://www.retro-games.hu/images/stories/virtuemart/product/PCENB0166.jpg",
      price: 5000,
      stock: 1,
      featured: false,
      active: true,
      onsale: false
    },
    {
      id: 129,
      catId: 0,
      name: "Microsoft Entertainment Pack 3",
      description: "papírdobozos, első kiadás, angol feliratos papírdobozos, angol nyelvű dokumentációk, 1db 3,5 floppy, angol nyelvű játék",
      image: "https://www.retro-games.hu/images/stories/virtuemart/product/PCENB0179.jpg",
      price: 4000,
      stock: 1,
      featured: false,
      active: true,
      onsale: false
    },
    {
      id: 130,
      catId: 0,
      name: "Microsoft Football: Action So Real It Hurts",
      description: "papírdobozos, első kiadás, angol feliratos papírdoboz, segédanyagok, regisztrációs kártya, cd tokban az eredeti cd, angol nyelvű játék",
      image: "https://www.retro-games.hu/images/stories/virtuemart/product/PCENB0189.jpg",
      price: 4000,
      stock: 1,
      featured: false,
      active: true,
      onsale: false
    },
    {
      id: 131,
      catId: 0,
      name: "Sensible Soccer 98",
      description: "papírdobozos, első kiadás, angol feliratos papírdobozos, angol nyelvű papírkézikönyv, regisztrációs kártya, cd tokban az eredeti cd, angol nyelvű játék",
      image: "https://www.retro-games.hu/images/stories/virtuemart/product/PCENB0251.jpg",
      price: 4000,
      stock: 1,
      featured: true,
      active: true,
      onsale: false
    },
    {
      id: 132,
      catId: 0,
      name: "Star Crusader",
      description: "papírdobozos, első kiadás, angol/német/francia feliratos papírdobozos, német nyelvű papírkézikönyv, cd tokban az eredeti cd, német nyelvű játék",
      image: "https://www.retro-games.hu/images/stories/virtuemart/product/PCENB0275.jpg",
      price: 3000,
      stock: 1,
      featured: false,
      active: true,
      onsale: false
    },
    {
      id: 133,
      catId: 0,
      name: "Steel Empire",
      description: "papírdobozos, első kiadás, angol/német/francia/olasz feliratos papírdobozos, német nyelvű papírkézikönyv, angol/német/francia/olasz nyelvű quickstart guide, angol feliratos kihajtható színes papírtérkép, regisztrációs kártya, 3db 3,5 floppy, angol nyelvű játék",
      image: "https://www.retro-games.hu/images/stories/virtuemart/product/PCENB0284.jpg",
      price: 4000,
      stock: 1,
      featured: false,
      active: true,
      onsale: false
    },
    {
      id: 134,
      catId: 0,
      name: "Vikings: The Strategy Of Ultimate Conquest",
      description: "papírdobozos, első kiadás, USA kiadás, angol feliratos papírdobozos, angol nyelvű papírkézikönyv a cd tokban, cd tokban az eredeti cd, angol nyelvű játék",
      image: "https://www.retro-games.hu/images/stories/virtuemart/product/PCENB0320.jpg",
      price: 3500,
      stock: 1,
      featured: false,
      active: true,
      onsale: false
    },
    {
      id: 135,
      catId: 0,
      name: "Walls Of Rome",
      description: "papírdobozos, első kiadás, USA kiadás, angol feliratos papírdobozos, angol nyelvű papírkézikönyv, 3db 2,5 floppy, angol nyelvű játék",
      image: "https://www.retro-games.hu/images/stories/virtuemart/product/PCENB0323.jpg",
      price: 3500,
      stock: 1,
      featured: false,
      active: true,
      onsale: false
    },
    {
      id: 136,
      catId: 0,
      name: "Avalon Hill's Diplomacy",
      description: "papírdobozos, első kiadás, angol feliratos papírdobozos, angol nyelvű papírkézikönyv, cd tokban az eredeti cd, angol nyelvű játék",
      image: "http://www.retro-games.hu/images/stories/virtuemart/product/PCENB0377.jpg",
      price: 4000,
      stock: 1,
      featured: false,
      active: true,
      onsale: false
    },
    {
      id: 137,
      catId: 0,
      name: "Crusaders: Thy Kingdom Come",
      description: "kis kartondobozos, első kiadás, angol/francia/német/olasz/spanyol/portugál feliratos borító, angol/francia/német/olasz/spanyol/portugál nyelvű papírkézikönyv, eredeti dvd, angol nyelvű játék. DVD állapota: karcmentes, újnak tűnik",
      image: "http://www.retro-games.hu/images/stories/virtuemart/product/PCENB0380.jpg",
      price: 3000,
      stock: 1,
      featured: false,
      active: true,
      onsale: true
    },
    {
      id: 138,
      catId: 0,
      name: "Combat Mission",
      description: "papírdobozos, első kiadás, angol feliratos papírdobozos (kartondoboz + csúsztatható borító), 200 oldalas angol nyelvű papírkézikönyv, eredeti cd + kiegészítő bónusz cd, angol nyelvű játék",
      image: "https://www.retro-games.hu/images/stories/virtuemart/product/PCENBOX0358.jpg",
      price: 5000,
      stock: 2,
      featured: false,
      active: true,
      onsale: false
    }

  ];
  static list: any;

  getFeaturedFive(): Product[] {
    const topFiveFeaturedProducts: Product[] = this.list.filter(product => product.featured)
      .sort(() => 0.5 - Math.random())
      .slice(0, 5);
    return topFiveFeaturedProducts;
  };

  getOnsaleFive() {
    const onsaleProducts: Product[] = this.list.filter(product => product.onsale)
      .sort(() => 0.5 - Math.random())
      .slice(0, 5);

    onsaleProducts.forEach(item => {
      item.price = item.price * 0.8
    });

    return onsaleProducts;
  }

  getCategoryProducts(category: number) {
    const categoryProducts: Product[] = this.list.filter(product => category === product.catId);
    return categoryProducts;
  }
  constructor() { }
}
